version: '3.8'

services:
  npa-vote:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3001:3000'
    command: bun run src/index.ts
    env_file:
      - stack.env
